### ISSUE TITLE
Create new user tiers

### ISSUE THREAD

**Issue by pierrelefevre** [kthcloud/go-deploy#150]
- Base user (KTH SSO) 
  - 1 core 
  - 4 GB ram 
  - 20 GB storage
  - 5 deployments
  - No GPU

- Middle tier
  - 8 cores
  - 50 GB ram
  - 500 GB storage
  - 20 Deployments
  - Autoselect B tier GPU

- Power User
  - 20 cores 
  - 100GB ram 
  - 2 TB storage
  - 100 Deployments
  - Choose GPU (Access to A tier RTX cards)

- Admin
  - Unlimited

**Comment by saffronjam** [comment]
fixed in https://github.com/kthcloud/go-deploy/pull/151
