### ISSUE TITLE
Debug custom domain

### ISSUE THREAD

**Issue by pierrelefevre** [kthcloud/go-deploy#195]
Creating a deployment with custom domain is not working 
- test with landing beta https://landing-beta.app.cloud.cbh.kth.se/deploy
- some test domains are CNAMEd to app.cloud.cbh.kth.se so should work

Domains CNAMEd to app.cloud.cbh.kth.se for testing purposes:
- test.pierrelf.com
- test2.pierrelf.com
- test3.pierrelf.com
- test4.pierrelf.com
- test5.pierrelf.com

DNS resolves to correct IP:

```
Result for test4.pierrelf.com/A with DNSSEC validation and without DNSSEC detail:
{
  "Status": 0 /* NOERROR */,
  "TC": false,
  "RD": true,
  "RA": true,
  "AD": false,
  "CD": false,
  "Question": [
    {
      "name": "test4.pierrelf.com.",
      "type": 1 /* A */
    }
  ],
  "Answer": [
    {
      "name": "test4.pierrelf.com.",
      "type": 5 /* CNAME */,
      "TTL": 300,
      "data": "app.cloud.cbh.kth.se."
    },
    {
      "name": "app.cloud.cbh.kth.se.",
      "type": 1 /* A */,
      "TTL": 60,
      "data": "130.237.83.247"
    }
  ],
  "Comment": "Response from 130.237.83.246."
}
```

Testing creation of deployment with params:
```
{
  "name": "nginx",
  "envs": [
    {
      "name": "PORT",
      "value": "80"
    }
  ],
  "volumes": [],
  "image": "nginx",
  "customDomain": "test4.pierrelf.com"
}
```

Results in:
`Error creating deployment: Custom domain must be a valid domain name and point to the correct interface`

**Comment by saffronjam** [comment]
resolved in https://github.com/kthcloud/go-deploy/pull/207
