### ISSUE TITLE
Create storage bucket when first logged in, add URL to user object

### ISSUE THREAD

**Issue by pierrelefevre** [kthcloud/go-deploy#238]
Instead of only creating storage bucket and deploying storage manager when attaching storage to deployment, create it when first logging in. 

Add URL for storage to user object perhaps? And later when frontend is updated, remove the field from deployment object?

Also is it possible to transfer via scp or other protocols for bigger files that may not fit in web ui transfer limits

**Comment by saffronjam** [comment]
storage manager is created automatically when interacting with deployments #240
