### ISSUE TITLE
Cannot update deployment when at quota

### ISSUE THREAD

**Issue by pierrelefevre** [kthcloud/go-deploy#309]
Possible bug: when i have 5 deployments i cant edit any environment variables. Basic tier

![Screenshot_20231210-135229_Firefox_1.jpg](https://github.com/kthcloud/go-deploy/assets/35996839/ef879be6-d4c4-4785-88c6-f8f6b2b822fb)

**Comment by pierrelefevre** [comment]
Seems this is all paths of update deployment, another user reported issues with editing health check path when at full quota

**Comment by saffronjam** [comment]
fixed in https://github.com/kthcloud/go-deploy/pull/316
