### ISSUE TITLE
Investigate slow rolling restart

### ISSUE THREAD

**Issue by pierrelefevre** [kthcloud/go-deploy#311]
"When a new deployment is sent through either CLI or Github actions the deployment goes down during the build process and displays "502 Bad Gateway". And when it's done it goes back to 200 and works as intended (takes ca 2-10min)"
from discord https://discord.com/channels/956593893300899891/1183689506856120391/1183691186444193833

**Comment by saffronjam** [comment]
Probably caused by a docker image that built on start. Meaning, K8s think it is ready earlier that it is, and kills the old pod
