### ISSUE TITLE
Add CLI

### ISSUE THREAD

**Issue by pierrelefevre** [kthcloud/go-deploy#327]
Use 
https://github.com/charmbracelet/bubbletea

Feature parity with frontend

**Comment by saffronjam** [comment]
![image](https://github.com/kthcloud/go-deploy/assets/26722370/73ba363b-ae6d-41e1-8683-c914abeda89a)

**Comment by pierrelefevre** [comment]
https://github.com/danielgtaylor/openapi-cli-generator
