### ISSUE TITLE
Debug no route to host

### ISSUE THREAD

**Issue by pierrelefevre** [kthcloud/go-deploy#341]
![image](https://github.com/kthcloud/go-deploy/assets/35996839/83c637b4-5064-4d79-b325-17be34227592)

**Comment by pierrelefevre** [comment]
vm id bee55fec-ebe4-4cbd-9c83-98a828829238

**Comment by pierrelefevre** [comment]
same issue vm baacf5a7-2a69-4dd5-bbbe-a3aa759b444c

**Comment by saffronjam** [comment]
This was temporarily resolved by recreating the virtual router.

**Comment by pierrelefevre** [comment]
Deprecated VM v1 issue
