### ISSUE TITLE
Investigate datetime lag

### ISSUE THREAD

**Issue by pierrelefevre** [kthcloud/go-deploy#346]
User reports: 
Hello, I've noticed that the system date/time setting is lagging behind. For example, now my VPS was showing a time of 10:08 UTC before I used ntpdate ntp.ubuntu.com to get it right again, and now it is showing 11:34 (as it should). I have now set this in my crontab to run daily, but it's a weird issue I've never before come across. Maybe something you might want to investigate

**Comment by pierrelefevre** [comment]
@saffronjam Haven't heard any news about this, should we call it stale and close the issue for now?

**Comment by f-r00t** [comment]
Hello, I posted this issue. Seems like the ntp service crashes:

`× ntp.service - Network Time Service
     Loaded: loaded (/lib/systemd/system/ntp.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2024-01-10 03:10:07 UTC; 3 weeks 2 days ago
       Docs: man:ntpd(8)
   Main PID: 697 (code=exited, status=255/EXCEPTION)
        CPU: 50.309s

Jan 05 15:03:01 xkr-kth ntpd[697]: 193.182.111.13 local addr 10.1.1.169 -> <null>
Jan 10 03:09:13 xkr-kth ntpd[697]: Soliciting pool server 2a01:3f7:5:2::1
Jan 10 03:09:31 xkr-kth ntpd[697]: Soliciting pool server 147.78.228.41
Jan 10 03:09:32 xkr-kth ntpd[697]: Soliciting pool server 83.168.200.198
Jan 10 03:09:33 xkr-kth ntpd[697]: Soliciting pool server 194.58.207.148
Jan 10 03:10:06 xkr-kth ntpd[697]: Soliciting pool server 194.58.202.148
Jan 10 03:10:06 xkr-kth ntpd[697]: Soliciting pool server 194.58.206.148
Jan 10 03:10:07 xkr-kth systemd[1]: ntp.service: Main process exited, code=exited, status=255/EXCEPTION
Jan 10 03:10:07 xkr-kth systemd[1]: ntp.service: Failed with result 'exit-code'.
Jan 10 03:10:07 xkr-kth systemd[1]: ntp.service: Consumed 50.309s CPU time.`

I don't know if this helps :)

**Comment by pierrelefevre** [comment]
Got one more report from a user (orb vm) that got 5 minutes time dilation over a month. 

Let's try and fix this in the cloud-init template, and provide a fix script for current VM users

**Comment by pierrelefevre** [comment]
VM v1 is deprecated, we can close this issue now
