### ISSUE TITLE
customDomainStatus "active" when everything is up and running

### ISSUE THREAD

**Issue by pierrelefevre** [kthcloud/go-deploy#375]
"ready" is unclear, ready for what? "active" seems more fit for when the deployment customdomain is up and running

**Comment by saffronjam** [comment]
![image](https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExaGZ0ZHB5c3J5NDFxYm1keGxuMXRiNW1wdmhmN3Npa3BibGZybHI4ciZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3aGZA6WLI9Jde/giphy.gif)
