### ISSUE TITLE
List replica status like Rancher

### ISSUE THREAD

**Issue by pierrelefevre** [kthcloud/go-deploy#426]
When containercreating, the service is not running. However the deployment.status field shows running.

Maybe we could have something like restarting, or creating. Something to indicate it isn't running

**Comment by saffronjam** [comment]
K8s is kinda weird about restarting though. What happens if you have replicas? How many replicas should be in "containercreating" for the deployment to be considered restart? And what about if some pod fails, the pod will be restarted, which means we get "restarting" in weird scenarios
