### ISSUE TITLE
Fix VM that cant be deleted

### ISSUE THREAD

**Issue by saffronjam** [kthcloud/go-deploy#454]
ID: 57376712-3bcb-48d7-9254-8bc75b6d1113

**Comment by saffronjam** [comment]
failed to delete vm. details: failed to delete cs for vm 57376712-3bcb-48d7-9254-8bc75b6d1113. details: failed to delete cs vm 0b066da2-b1f5-41c5-88be-2cde57a65c5c. details: Undefined error: {\"errorcode\":530,\"errortext\":\"Error while process answer: class com.cloud.agent.api.DeleteVMSnapshotAnswer due to null\"}

Probably need DB intervention

**Comment by pierrelefevre** [comment]
Can probably close this VM v1 issue
