### ISSUE TITLE
Move API client collection to Bruno

### ISSUE THREAD

**Issue by pierrelefevre** [kthcloud/go-deploy#457]
Postman is severely limiting our ability to share the API client collection with the entire team - maybe we can switch to Bruno? Fully open source and supports git version control of the collection, so we can just store it in a kthcloud repo.

https://www.usebruno.com/compare/bruno-vs-postman

Supports importing Postman collections so should be pretty plug and play

**Comment by saffronjam** [comment]
Repo created at https://github.com/kthcloud/bruno

However, Bruno is not ready yet as it lacks many features.

Closing this issue for now
