### ISSUE TITLE
CI/CD npm package added in #466

### ISSUE THREAD

**Issue by pierrelefevre** [kthcloud/go-deploy#470]
We should build the kthcloud-types npm package in GitHub Actions so it always matches with the go-deploy types.

**Comment by pierrelefevre** [comment]
Hmm seems https://github.com/kthcloud/go-deploy/commit/c1870e930d49ac42c99e372c23832b2aa25f8fc4 got us further but still some access error. Maybe a new token could help

**Comment by saffronjam** [comment]
Published to https://www.npmjs.com/package/go-deploy-types?activeTab=readme

Using GitHub action `.github/workflows/npm-package.yml`
