### ISSUE TITLE
Setting userData returns 500 

### ISSUE THREAD

**Issue by pierrelefevre** [kthcloud/go-deploy#472]
Both update and explicit create methods are returning 500.

Tested with:

```
POST https://api.cloud.cbh.kth.se/deploy/v1/userData/onboarded 
{"data":"true"}
```

```
POST https://api.cloud.cbh.kth.se/deploy/v1/userData 
{"id":"onboarded","data":"true"}
```

POST /user***s***Data returns 404 although it is in the Swagger docs. Filed a separate issue #471

**Comment by saffronjam** [comment]
I cannot reproduce, works both with admin account and test account

**Comment by saffronjam** [comment]
Appears to have been fixed in previous PRs.

**Comment by pierrelefevre** [comment]
@saffronjam Seems the issue still persists
