### ISSUE TITLE
Check if gravatar exists for each user, if so add field

### ISSUE THREAD

**Issue by pierrelefevre** [kthcloud/go-deploy#553]
Check if gravatar exists for each user, can use the same route used in the frontend.

If it exists, the url can be in the profile as an optional field.

**Comment by pierrelefevre** [comment]
https://github.com/kthcloud/console/blob/main/src/components/Gravatar.tsx

**Comment by pierrelefevre** [comment]
see the code

**Comment by pierrelefevre** [comment]
if you want

**Comment by pierrelefevre** [comment]
it's nice, I wrote it myself

**Comment by saffronjam** [comment]
![image](https://github.com/kthcloud/go-deploy/assets/26722370/36da93c6-a905-459f-babc-8252ca6c276d)

**Comment by saffronjam** [comment]
![image](https://github.com/kthcloud/go-deploy/assets/26722370/b424ee74-8160-48ad-b7c6-d70d89c3ae9a)
