### ISSUE TITLE
Include gravatar in Team member object

### ISSUE THREAD

**Issue by pierrelefevre** [kthcloud/go-deploy#561]
```json
                "id": "0776e928-85e6-4b4c-8a11-1ce8e8deefe2",
                "username": "test@test.com",
                "email": "test@test.com",
                "teamRole": "admin",
                "memberStatus": "joined",
                "joinedAt": "2023-12-19T16:30:51.158Z",
                "addedAt": "2023-12-19T16:30:51.158Z"
```
wher url

**Comment by pierrelefevre** [comment]
![image](https://github.com/kthcloud/go-deploy/assets/35996839/7892a7c3-e107-411c-aeea-408e1b7d7b6a)

**Comment by saffronjam** [comment]
Holy shit what an ugly cat

**Comment by saffronjam** [comment]
Added to User discovery too, if you want those:

![image](https://github.com/kthcloud/go-deploy/assets/26722370/8a10d4ce-e69f-4dfd-9c2c-11d952c2644a)

For every user when searching

**Comment by pierrelefevre** [comment]
![Just picked up this little one_ Meet Bartholomew!](https://github.com/kthcloud/go-deploy/assets/35996839/0cb4d518-05bf-4bed-ad27-b3c323086bf5)

**Comment by saffronjam** [comment]
Enormous cats 🐱 

<img src="https://i.redd.it/h5ryplby2cf81.jpg"></img>
