### ISSUE TITLE
Update to new logo

### ISSUE THREAD

**Issue by pierrelefevre** [kthcloud/go-deploy#576]
https://github.com/kthcloud/branding/tree/main/go-deploy-logo

🙏🏻 no more AI generated logo 🙏🏻

**Comment by pierrelefevre** [comment]
<div class="tenor-gif-embed" data-postid="22309724" data-share-method="host" data-aspect-ratio="1.78771" data-width="100%"><a href="https://tenor.com/view/pay-respects-press-f-call-of-duty-respect-press-x-gif-22309724">Pay Respects Press F GIF</a>from <a href="https://tenor.com/search/pay+respects-gifs">Pay Respects GIFs</a></div> <script type="text/javascript" async src="https://tenor.com/embed.js"></script>

**Comment by pierrelefevre** [comment]
https://media1.tenor.com/m/BZ4V-B05un8AAAAd/pay-respects-press-f.gif

**Comment by pierrelefevre** [comment]
<img src="https://media1.tenor.com/m/BZ4V-B05un8AAAAd/pay-respects-press-f.gif"/>

**Comment by pierrelefevre** [comment]
also update here 🙏🏻 https://api.cloud.cbh.kth.se/deploy

**Comment by saffronjam** [comment]
He will be missed 😭
