### ISSUE TITLE
Run tsc after building types

### ISSUE THREAD

**Issue by pierrelefevre** [kthcloud/go-deploy#641]
We could run TSC after building the types in `build-types.yml`, which would return any potential TS errors immediately

**Comment by pierrelefevre** [comment]
![Screenshot_20240603-220004.png](https://github.com/kthcloud/go-deploy/assets/35996839/620e3edb-d087-4ca1-8d4d-31a585f17cb5)

tsc

**Comment by saffronjam** [comment]
![image](https://github.com/kthcloud/go-deploy/assets/26722370/29142fb7-baac-44a1-b981-6ec11f179c1d)

**Comment by pierrelefevre** [comment]
install typescript!
