### ISSUE TITLE
Renaming vm resets the disk

### ISSUE THREAD

**Issue by pierrelefevre** [kthcloud/go-deploy#655]
When renaming a vm, it seems to create a brand new vm. 

The disk is reset to the base vm

Steps to reproduce: 
1. Create VM & SSH into it
2. Install some stuff, create some files
3. Rename VM
4. SSH back in (VM will have a new identity!!)
5. Everything is gone

**Comment by pierrelefevre** [comment]
@saffronjam Should we create a banner alert for this for now? Would be unfortunate for someone to lose all their data

**Comment by saffronjam** [comment]
No need, fix already implemented!
