### ISSUE TITLE
VM HttpProxy uses Kubernetes Fake Certificate

### ISSUE THREAD

**Issue by pierrelefevre** [kthcloud/go-deploy#657]
![image](https://github.com/kthcloud/go-deploy/assets/35996839/cd5e1197-6d71-4b43-97f6-c5d9877aeaff)

https://galactus.a3roy2xvdwquy29tiglzigegcmvhbgx5ignvb2wgc2l0zsbnbyb0agvyzsbub3c.online/

VM ID 662b8565-2b37-4f31-9f88-fd212c97bbdf

**Comment by saffronjam** [comment]
Might be related to the underling CertManager having a new API. go-deploy does everything it "should" do.

**Comment by pierrelefevre** [comment]
![image](https://github.com/kthcloud/go-deploy/assets/35996839/dcd8150f-94a6-4f59-9945-706a9c85e471)
poor cert manager

**Comment by pierrelefevre** [comment]
true tho

**Comment by pierrelefevre** [comment]
we're only concerned about if CertManager is working, not how CertManager is feeling :'(

**Comment by pierrelefevre** [comment]
#justiceForCertManager

**Comment by saffronjam** [comment]
Por CertManger :(

**Comment by pierrelefevre** [comment]
![image](https://github.com/kthcloud/go-deploy/assets/35996839/ff70c317-643e-4550-bfc1-90812ee24c6a)

how will I know if this is the real cat website or man in the middle :(

**Comment by saffronjam** [comment]
Fixed by removing hairpin proxy installation and enabling NAT reflection in firewall.
